version: '3.9'

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
      - ./logs:/app/logs
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    volumes:
      - ./dev_db_data:/var/opt/mssql/data
    env_file:
      - .env
    ports:
      - 1434:1433
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S 162.0.213.111 -U Smar_user -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

volumes:
  static-data:

networks:
  default:
    name: cluster_default
    external: true
