# Generated by Django 4.0.10 on 2024-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categories_menuitems_orders_payments_orders_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='image5',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
