# Generated by Django 4.0.10 on 2024-02-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_time',
            field=models.TimeField(null=True),
        ),
    ]
