# Generated by Django 4.0.10 on 2024-02-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_categories_last_update_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extras',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large', models.BooleanField(blank=True, default=False, null=True)),
                ('medium', models.BooleanField(blank=True, default=False, null=True)),
                ('small', models.BooleanField(blank=True, default=False, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_update_login', models.IntegerField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.menuitems')),
            ],
        ),
        migrations.CreateModel(
            name='KitchenNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_update_login', models.IntegerField(blank=True, null=True)),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.menuitems')),
            ],
        ),
        migrations.AddField(
            model_name='orderitems',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sizes'),
        ),
    ]
