# Generated by Django 4.0.10 on 2024-02-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_extras_price_alter_menuitems_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extras',
            old_name='items',
            new_name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
        migrations.AddField(
            model_name='cart',
            name='extras',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='kitchen_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='extras',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='kitchen_notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
