# Generated by Django 4.0.10 on 2024-02-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_items_extras_menu_item_remove_orders_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='size',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
