# Generated by Django 4.0.10 on 2024-02-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cart_size_alter_orderitems_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='large_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='small_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
