# Generated by Django 4.0.10 on 2024-02-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_menuitems_large_price_menuitems_small_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='medium_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
