# Generated by Django 4.0.10 on 2024-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ordernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotifications',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='last_update_login',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='last_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
