# Generated by Django 4.0.10 on 2024-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_categories_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='last_update_login',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitems',
            name='last_updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
