# Generated by Django 4.0.10 on 2024-04-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_menuitems_created_by_menuitems_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='large_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='medium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='small_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
