# Generated by Django 4.0.10 on 2024-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_menuitems_large_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid_by_points',
            field=models.BooleanField(default=False),
        ),
    ]
