# Generated by Django 4.0.10 on 2024-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_payments_paid_by_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
